INSERT INTO salesforce_document
            (salesforce_document_id,
             id_salesforce_tariff,
             id_salesforce_special_offer,
             id_salesforce_product,
             "name",
             has_personal_manager,
             has_express_delivery,
             has_credit,
             report_server_id,
             preview,
             contract_atachment,
             format,
             short_name,
             summary_name,
             internal,
             num_pages,
             priority,
             need_signature,
             salesforce_type_document_id,
             is_spec_partner,
             partner_program_name)
VALUES     (136,
            32,
            NULL,
            1,
'Приложение E2E акция цена стелы на РН на АИ-95'
            ,
NULL,
NULL,
NULL,
'10132',
NULL,
false,
'PDF',
'Приложение E2E акция цена стелы на РН на АИ-95'
            ,
'Приложение E2E акция цена стелы на РН на АИ-95'
            ,
false,
'1 л',
2,
true,
9,
NULL,
NULL); 

INSERT INTO salesforce_document
            (salesforce_document_id,
             id_salesforce_tariff,
             id_salesforce_special_offer,
             id_salesforce_product,
             "name",
             has_personal_manager,
             has_express_delivery,
             has_credit,
             report_server_id,
             preview,
             contract_atachment,
             format,
             short_name,
             summary_name,
             internal,
             num_pages,
             priority,
             need_signature,
             salesforce_type_document_id,
             is_spec_partner,
             partner_program_name)
VALUES     (137,
            33,
            NULL,
            1,
'Приложение E2E акция цена стелы на РН на АИ-95'
            ,
NULL,
NULL,
NULL,
'10132',
NULL,
false,
'PDF',
'Приложение E2E акция цена стелы на РН на АИ-95'
            ,
'Приложение E2E акция цена стелы на РН на АИ-95'
            ,
false,
'1 л',
2,
true,
9,
NULL,
NULL); 
