global with sharing class OpportunityGlobalTextUtils {

    public final String OPPORTUNITY_NAME = 'Opportunity';
    public final String USA_OPPORTUNITY_RECORD_TYPE_NAME = 'USA_opportunity';
    public final String UK_OPPORTUNITY_RECORD_TYPE_NAME = 'UK_opportunity';
    public final String OPPORTUNITY_COUNTRY_USA = 'USA';
    public final String OPPORTUNITY_NEW_CUSTOMER = 'New Customer';
    public final String OPPORTUNITY_DESCRIPTION = 'New possibility of processing within an hour';
    public final String OPPORTUNITY_NEXT_STEP = 'Make a client';
    public final String OPPORTUNITY_LEAD_SOURCE = 'Web';
    public final String OPPORTUNITY_DELIVERY_INSTALLATION_STATUS = 'In progress';
    public final String OPPORTUNITY_LIST_ERROR = 'Opportunity list is empty';
}